version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env


    # environment:
    #   - SERVER_ADDRESS=localhost:8080
    #   - SERVER_PORT=8080
    #   - RANDOM_SECRET=RANDOM_SECRET
    #   - ENVIRONMENT=producti

  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres:16.6
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=promo
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data


# volumes:
#   postgres_data:
